### ISSUE TITLE
the question about evaluation metrics

### ISSUE THREAD

**Issue by lsnls** [Junzhou-Chen/EADB-Net#1]
Hi, @Junzhou-Chen !

Thank you for your valuable work! The paper mentioned three evaluation metrics: Dice, PQ and AJI. Could you pls clarify what type of prediction masks all the metrics are based on? Are they calculated from **binary semantic segmentation masks** or **instance segmentation masks**?

I appreciate your help and look forward to your response!

Best regards,
Suoni

**Comment by Junzhou-Chen** [comment]
Hi Suoni

The Dice is for the binary semantic segmentation masks, and the PQ and the AJI are for the instance segmentation masks.

Best,
Junzhou

**Comment by lsnls** [comment]
I got it! Thank you again!
